- name: PLAY-1
  host: local
  connection: local
  tasks:
  - name: PLAY1 and TASK1
    ansible.builtin.debug:
      msg: "Hello from PLAY1 and TASK1"

- name: PLAY-2
  host: local
  connection: local
  tasks:
  - name: PLAY2 and TASK1
    ansible.builtin.debug:
      msg: "Hello from PLAY2 and TASK1"