- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with aws"
    DURATION: 120hrs
  tasks:
  - name: print the variable
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "course is {{COURSE}} , duration is {{DURATION}}"

  - name: print the variable1
    ansible.builtin.debug:
      msg: "Course is {{COURSE}} , duration is {{DURATION}}"