- name: print the variables from another variable file
  hosts: local
  connection: local
  vars_files:
  - name: COURSE
    prompt: please enter your course name
    private: false
  - name: DURATION
    prompt: please enter your course duration
    private: false


  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, duration is {{DURATION}},"